function ant = makeIdealCpAntenna(handedness, position, boresight, h_axis, v_axis)
% makeIdealCpAntenna - ideal circularly polarized antenna factory.

    if nargin < 1 || isempty(handedness)
        handedness = 'right';
    end
    hand = lower(char(string(handedness)));
    assert(ismember(hand, {'right', 'left', 'r', 'l'}), 'handedness must be right/left');

    if startsWith(hand, 'l')
        primary_handedness = 'L';
    else
        primary_handedness = 'R';
    end

    ant = core.Antenna( ...
        'position', position(:), ...
        'boresight', boresight(:), ...
        'h_axis', h_axis(:), ...
        'v_axis', v_axis(:), ...
        'basis', 'circular', ...
        'convention', 'IEEE-RHCP', ...
        'cross_pol_leakage_db', 60.0, ...
        'axial_ratio_db', 0.0, ...
        'enable_coupling', false, ...
        'tx_peak_gain_dbi', 0.0, ...
        'rx_peak_gain_dbi', 0.0, ...
        'tx_pattern_cos_exp', 0.0, ...
        'rx_pattern_cos_exp', 0.0, ...
        'patternData', struct('port_count', 2, 'primary_handedness', primary_handedness, 'factory', 'ideal_cp'));
end
