function [cases, meta] = designStage2RecoveryMiniCases(candidate_ranking_csv, day3_summary_md)
% designStage2RecoveryMiniCases - Day 4 Stage 2 room mini sweep design.
%
% The design translates the Day 3 Stage 1 outcomes into Stage 2 room cases:
%   P1_MAIN : low effective eps proxy + xpol 30-38 + floor/ceiling-like geometry
%   P2_SENS : low effective eps + mid xpol + moderate/high SNR sensitivity band
%   P3_CTRL : high effective eps or wall-dominant negative control
%
% Layout:
%   - 90 baseline coverage cases per room from generateRoomTxRxGrid
%   - 90 targeted cases per room (30 per candidate, 10 points x 3 parameter combos)
%   - total = 540 cases, patch_ffd only

    if nargin < 1 || isempty(candidate_ranking_csv)
        repo_root = fileparts(fileparts(mfilename('fullpath')));
        candidate_ranking_csv = fullfile(repo_root, 'results', 'recovery_mini', 'day3', 'day3_stage1_recovery_mini_candidate_ranking.csv');
    end
    if nargin < 2 || isempty(day3_summary_md)
        repo_root = fileparts(fileparts(mfilename('fullpath')));
        day3_summary_md = fullfile(repo_root, 'results', 'recovery_mini', 'day3', 'day3_stage1_recovery_mini_summary.md');
    end

    assert(exist(candidate_ranking_csv, 'file') == 2, 'Day 3 candidate ranking CSV not found: %s', candidate_ranking_csv);
    assert(exist(day3_summary_md, 'file') == 2, 'Day 3 summary report not found: %s', day3_summary_md);

    ranking = readtable(candidate_ranking_csv, 'TextType', 'string');
    assert(any(ranking.candidate_id == "C1"), 'Day 3 ranking must contain C1.');

    room_types = ["A", "B", "C"];
    room_size = [5.0, 4.0, 3.0];
    anchor = [room_size(1) / 2.0, room_size(2) / 2.0, room_size(3) - 0.30];

    seed_stage_id = "stage2_recovery_room_mini_day4";
    seed_base = 20260424;
    label_rule = "mixed_0p33_primary";
    n_uniform_per_room = 90;

    rows = {};
    case_id = 0;
    for room_idx = 1:numel(room_types)
        room_type = room_types(room_idx);
        [grid_tbl, ~] = scenes.generateRoomTxRxGrid(char(room_type), room_size, n_uniform_per_room, double(seed_base + room_idx));

        for i = 1:height(grid_tbl)
            case_id = case_id + 1;
            [snr_db, xpol_db, eps_mult, wall_mat] = baselineParams(i);
            rows(end + 1, :) = makeRow(case_id, seed_stage_id, seed_base, room_type, ...
                grid_tbl.anchor_x(i), grid_tbl.anchor_y(i), grid_tbl.anchor_z(i), ...
                grid_tbl.tag_x(i), grid_tbl.tag_y(i), grid_tbl.tag_z(i), ...
                grid_tbl.grid_layer(i), snr_db, xpol_db, eps_mult, wall_mat, ...
                "BASE", "uniform_room_coverage", label_rule, ...
                "Layer1+2 baseline room coverage from generateRoomTxRxGrid", 1); %#ok<AGROW>
        end

        targeted = buildTargetedCasesForRoom(room_type, anchor, seed_stage_id, seed_base, label_rule);
        for i = 1:numel(targeted)
            case_id = case_id + 1;
            t = targeted(i);
            rows(end + 1, :) = makeRow(case_id, seed_stage_id, seed_base, room_type, ...
                anchor(1), anchor(2), anchor(3), ...
                t.tag_x, t.tag_y, t.tag_z, ...
                t.grid_layer, t.snr_db, t.xpol_coupling_db, t.eps_r_multiplier, t.dominant_wall_material, ...
                t.expected_candidate_id, t.expected_condition, label_rule, t.notes, t.replicate_id); %#ok<AGROW>
        end
    end

    cases = cell2table(rows, 'VariableNames', { ...
        'case_id', 'seed_stage_id', 'seed_base', 'stage_id', 'base_seed', ...
        'room_type', 'grid_layer', 'anchor_x', 'anchor_y', 'anchor_z', 'tag_x', 'tag_y', 'tag_z', ...
        'snr_db', 'xpol_coupling_db', 'eps_r_multiplier', 'dominant_wall_material', ...
        'expected_candidate_id', 'expected_condition', 'label_rule', 'notes', 'replicate_id', ...
        'antenna_type', 'material_name'});

    cases = addLosGeometryColumns(cases);
    cases = sortrows(cases, {'room_type', 'expected_candidate_id', 'grid_layer', 'snr_db', 'xpol_coupling_db', 'eps_r_multiplier'});
    cases.case_id = (1:height(cases)).';

    meta = struct();
    meta.seed_stage_id = seed_stage_id;
    meta.seed_base = seed_base;
    meta.total_cases = height(cases);
    meta.cases_per_room = countsBy(cases, 'room_type');
    meta.cases_per_candidate = countsBy(cases, 'expected_candidate_id');
    meta.input_candidate_ranking = string(candidate_ranking_csv);
    meta.input_day3_summary = string(day3_summary_md);
    meta.day3_top_candidate = ranking.candidate_id(1);
end

function row = makeRow(case_id, seed_stage_id, seed_base, room_type, anchor_x, anchor_y, anchor_z, tag_x, tag_y, tag_z, grid_layer, snr_db, xpol_db, eps_mult, wall_mat, candidate_id, condition_name, label_rule, notes, replicate_id)
    row = { ...
        case_id, string(seed_stage_id), double(seed_base), string(seed_stage_id), double(seed_base), ...
        string(room_type), double(grid_layer), ...
        double(anchor_x), double(anchor_y), double(anchor_z), ...
        double(tag_x), double(tag_y), double(tag_z), ...
        double(snr_db), double(xpol_db), double(eps_mult), string(wall_mat), ...
        string(candidate_id), string(condition_name), string(label_rule), string(notes), double(replicate_id), ...
        "patch_ffd", string(wall_mat)};
end

function [snr_db, xpol_db, eps_mult, wall_mat] = baselineParams(idx)
    snr_cycle = [15, 25, 35];
    xpol_cycle = [22, 30, 38];
    eps_cycle = [0.88, 1.00, 1.12];
    mat_cycle = ["drywall", "concrete", "brick", "glass", "wood"];
    snr_db = snr_cycle(mod(idx - 1, numel(snr_cycle)) + 1);
    xpol_db = xpol_cycle(mod(idx - 1, numel(xpol_cycle)) + 1);
    eps_mult = eps_cycle(mod(idx - 1, numel(eps_cycle)) + 1);
    wall_mat = mat_cycle(mod(idx - 1, numel(mat_cycle)) + 1);
end

function targeted = buildTargetedCasesForRoom(room_type, anchor, seed_stage_id, seed_base, label_rule) %#ok<INUSD>
    point_sets = targetedPointSets(room_type);
    defs = candidateDefinitions();
    targeted = struct('tag_x', {}, 'tag_y', {}, 'tag_z', {}, 'grid_layer', {}, 'snr_db', {}, 'xpol_coupling_db', {}, 'eps_r_multiplier', {}, ...
        'dominant_wall_material', {}, 'expected_candidate_id', {}, 'expected_condition', {}, 'notes', {}, 'replicate_id', {});
    idx = 0;
    for d = 1:numel(defs)
        def = defs(d);
        pts = point_sets.(char(def.point_key));
        for p = 1:size(pts, 1)
            for c = 1:size(def.param_table, 1)
                idx = idx + 1;
                targeted(idx).tag_x = pts(p, 1); %#ok<AGROW>
                targeted(idx).tag_y = pts(p, 2);
                targeted(idx).tag_z = pts(p, 3);
                targeted(idx).grid_layer = pts(p, 4);
                targeted(idx).snr_db = def.param_table(c, 1);
                targeted(idx).xpol_coupling_db = def.param_table(c, 2);
                targeted(idx).eps_r_multiplier = def.param_table(c, 3);
                targeted(idx).dominant_wall_material = def.material_cycle(c);
                targeted(idx).expected_candidate_id = def.candidate_id;
                targeted(idx).expected_condition = def.condition_name;
                targeted(idx).notes = sprintf('%s translated from Day3 %s in Room %s', def.note, def.day3_source, room_type);
                targeted(idx).replicate_id = 100 * d + 10 * p + c;
            end
        end
    end
end

function defs = candidateDefinitions()
    defs = struct([]);

    defs(1).candidate_id = "P1_MAIN";
    defs(1).condition_name = "low_eps_proxy_xpol30to38_floor_ceiling_like";
    defs(1).point_key = "p1_points";
    defs(1).day3_source = "C1";
    defs(1).note = "Low effective eps proxy with floor/ceiling-like geometry";
    defs(1).param_table = [ ...
        25, 30, 0.88; ...
        35, 34, 0.92; ...
        25, 38, 0.96];
    defs(1).material_cycle = ["drywall", "concrete", "drywall"];

    defs(2).candidate_id = "P2_SENS";
    defs(2).condition_name = "low_eps_proxy_mid_xpol_high_snr_sensitivity";
    defs(2).point_key = "p2_points";
    defs(2).day3_source = "C2 conditional";
    defs(2).note = "Sensitivity band around Day3 conditional low-eps pockets";
    defs(2).param_table = [ ...
        25, 30, 0.88; ...
        35, 30, 0.90; ...
        35, 32, 0.94];
    defs(2).material_cycle = ["concrete", "drywall", "concrete"];

    defs(3).candidate_id = "P3_CTRL";
    defs(3).condition_name = "high_eps_or_wall_dominant_control";
    defs(3).point_key = "p3_points";
    defs(3).day3_source = "control";
    defs(3).note = "Higher effective eps or wall-dominant negative control";
    defs(3).param_table = [ ...
        15, 22, 1.08; ...
        25, 30, 1.12; ...
        35, 38, 1.18];
    defs(3).material_cycle = ["brick", "concrete", "brick"];
end

function point_sets = targetedPointSets(room_type)
    room_type = upper(char(string(room_type)));
    switch room_type
        case 'A'
            point_sets.p1_points = [ ...
                2.0, 2.0, 0.20, 1; ...
                3.0, 2.0, 0.20, 1; ...
                2.5, 1.4, 0.20, 1; ...
                2.5, 2.6, 0.20, 1; ...
                1.8, 1.5, 1.20, 1; ...
                3.2, 2.5, 1.20, 1; ...
                2.1, 2.3, 1.20, 1; ...
                2.9, 1.7, 1.20, 1; ...
                1.9, 2.8, 0.65, 1; ...
                3.1, 1.2, 0.65, 1];
            point_sets.p2_points = [ ...
                0.6, 2.0, 0.20, 2; ...
                4.4, 2.0, 1.20, 2; ...
                2.5, 0.55, 0.20, 2; ...
                2.5, 3.45, 1.20, 2; ...
                0.8, 0.8, 0.65, 2; ...
                4.2, 3.2, 0.65, 2; ...
                1.0, 3.0, 0.20, 2; ...
                4.0, 1.0, 1.20, 2; ...
                1.4, 0.6, 1.20, 2; ...
                3.6, 3.4, 0.20, 2];
            point_sets.p3_points = [ ...
                0.35, 0.5, 0.20, 2; ...
                4.65, 3.5, 1.20, 2; ...
                0.40, 3.4, 0.20, 2; ...
                4.60, 0.6, 1.20, 2; ...
                0.50, 2.0, 0.20, 2; ...
                4.50, 2.0, 0.20, 2; ...
                2.5, 0.35, 0.20, 2; ...
                2.5, 3.65, 0.20, 2; ...
                0.7, 3.6, 1.20, 2; ...
                4.3, 0.4, 1.20, 2];

        case 'B'
            point_sets.p1_points = [ ...
                1.8, 1.8, 0.20, 1; ...
                2.6, 1.7, 0.20, 1; ...
                2.0, 2.4, 0.20, 1; ...
                2.7, 2.2, 0.20, 1; ...
                1.9, 1.6, 1.20, 1; ...
                2.8, 2.0, 1.20, 1; ...
                2.2, 2.5, 1.20, 1; ...
                3.0, 1.5, 1.20, 1; ...
                1.7, 2.6, 0.65, 1; ...
                2.9, 1.4, 0.65, 1];
            point_sets.p2_points = [ ...
                4.45, 2.2, 0.65, 2; ...
                3.7, 2.5, 0.20, 2; ...
                3.6, 2.9, 1.20, 2; ...
                4.2, 1.8, 0.65, 2; ...
                3.0, 2.8, 0.20, 2; ...
                3.2, 2.1, 1.20, 2; ...
                4.0, 2.6, 0.20, 2; ...
                3.9, 1.4, 1.20, 2; ...
                3.4, 3.1, 0.65, 2; ...
                4.35, 2.9, 0.20, 2];
            point_sets.p3_points = [ ...
                4.55, 2.2, 0.20, 2; ...
                4.45, 2.8, 0.20, 2; ...
                3.9, 3.1, 0.20, 2; ...
                3.7, 2.9, 0.65, 2; ...
                4.6, 1.6, 1.20, 2; ...
                4.4, 3.4, 1.20, 2; ...
                3.5, 3.3, 0.20, 2; ...
                4.2, 0.6, 0.20, 2; ...
                3.8, 0.8, 1.20, 2; ...
                4.6, 2.5, 0.65, 2];

        case 'C'
            point_sets.p1_points = [ ...
                2.6, 2.0, 0.20, 1; ...
                3.2, 2.1, 0.20, 1; ...
                2.8, 1.5, 0.20, 1; ...
                3.4, 1.7, 0.20, 1; ...
                2.7, 2.2, 1.20, 1; ...
                3.5, 2.0, 1.20, 1; ...
                3.0, 1.4, 1.20, 1; ...
                3.6, 1.8, 1.20, 1; ...
                2.9, 2.4, 0.65, 1; ...
                3.7, 1.5, 0.65, 1];
            point_sets.p2_points = [ ...
                1.6, 3.2, 0.65, 2; ...
                1.9, 2.8, 0.20, 2; ...
                2.4, 1.5, 0.65, 2; ...
                2.7, 1.3, 1.20, 2; ...
                3.3, 2.4, 0.20, 2; ...
                3.8, 2.1, 1.20, 2; ...
                1.4, 2.6, 1.20, 2; ...
                2.2, 1.7, 0.20, 2; ...
                3.0, 1.9, 0.65, 2; ...
                4.0, 2.8, 0.65, 2];
            point_sets.p3_points = [ ...
                1.10, 3.55, 0.20, 2; ...
                1.25, 3.3, 0.65, 2; ...
                1.50, 3.6, 1.20, 2; ...
                2.30, 0.95, 0.20, 2; ...
                2.30, 1.05, 0.65, 2; ...
                2.60, 1.15, 1.20, 2; ...
                0.90, 3.0, 0.20, 2; ...
                1.80, 0.8, 1.20, 2; ...
                1.00, 3.7, 0.20, 2; ...
                2.80, 0.9, 0.20, 2];

        otherwise
            error('Unsupported room type: %s', room_type);
    end
end

function cases = addLosGeometryColumns(cases)
    anchor = [cases.anchor_x, cases.anchor_y, cases.anchor_z];
    tag = [cases.tag_x, cases.tag_y, cases.tag_z];
    delta = tag - anchor;
    los_dist = sqrt(sum(delta.^2, 2));
    los_dir = delta ./ max(los_dist, 1e-12);
    anchor_bore = repmat([0, 0, -1], height(cases), 1);
    tag_bore = repmat([0, 0, 1], height(cases), 1);

    cases.los_distance_m = los_dist;
    cases.los_angle_from_anchor_bore_deg = acosd(clamp(sum(los_dir .* anchor_bore, 2)));
    cases.los_angle_from_tag_bore_deg = acosd(clamp(sum((-los_dir) .* tag_bore, 2)));
end

function y = clamp(x)
    y = min(max(double(x), -1.0), 1.0);
end

function tbl = countsBy(cases, var_name)
    values = string(cases.(var_name));
    [G, labels] = findgroups(values);
    counts = splitapply(@numel, cases.case_id, G);
    tbl = table(labels, counts, 'VariableNames', {var_name, 'case_count'});
end
