function [cases, meta] = designStage1RecoveryMiniCases(candidate_csv_path)
% designStage1RecoveryMiniCases - deterministic Stage 1 mini sweep for Day 3 recovery validation.
%
% The design follows Day 2 shortlisted Stage 1 candidates:
%   C1: low eps_r broad regime
%   C2: low eps_r + mid xpol hotspot
%   C5: low-confidence rescue probe translated into physical controls
%
% Sparse ideal cases are included only as an upper-bound control.

    if nargin < 1 || isempty(candidate_csv_path)
        repo_root = fileparts(fileparts(mfilename('fullpath')));
        candidate_csv_path = fullfile(repo_root, 'results', 'recovery_mini', 'day2', 'day2_candidate_regimes.csv');
    end

    assert(exist(candidate_csv_path, 'file') == 2, 'Day 2 candidate CSV not found: %s', candidate_csv_path);
    shortlist = readtable(candidate_csv_path, 'TextType', 'string');

    required_ids = ["C1", "C2", "C5"];
    missing_ids = required_ids(~ismember(required_ids, string(shortlist.candidate_id)));
    assert(isempty(missing_ids), 'Missing Stage 1 shortlist ids in %s: %s', candidate_csv_path, strjoin(cellstr(missing_ids), ', '));

    seed_stage_id = "stage1_recovery_mini_day3";
    seed_base = 20260423;
    tan_delta = 0.01;
    ar_edge_db = 10.0;
    slab_size_base = 5.0;
    material_name = "recovery_mini_dielectric";

    blocks = { ...
        struct( ...
            'candidate_id', "C1", ...
            'expected_regime', "positive_low_eps_broad", ...
            'antenna_type', "patch_ffd", ...
            'eps_values', [2.5, 4.5], ...
            'xpol_values', [22, 30, 38], ...
            'inc_values', [20, 45, 65], ...
            'snr_values', [15, 25, 35], ...
            'placements', {{'floor', 'ceiling'}}, ...
            'replicates', 3, ...
            'notes', "Day2 C1 patch block around low-eps regime"), ...
        struct( ...
            'candidate_id', "C2", ...
            'expected_regime', "positive_low_eps_mid_xpol_hotspot", ...
            'antenna_type', "patch_ffd", ...
            'eps_values', [2.5, 4.5], ...
            'xpol_values', [30], ...
            'inc_values', [20, 45, 65], ...
            'snr_values', [15, 25, 35], ...
            'placements', {{'floor', 'ceiling'}}, ...
            'replicates', 6, ...
            'notes', "Day2 C2 hotspot oversampled for recovery stability"), ...
        struct( ...
            'candidate_id', "C5", ...
            'expected_regime', "positive_low_confidence_probe", ...
            'antenna_type', "patch_ffd", ...
            'eps_values', [2.5, 4.5], ...
            'xpol_values', [30, 38], ...
            'inc_values', [45, 65], ...
            'snr_values', [15, 25], ...
            'placements', {{'floor', 'ceiling'}}, ...
            'replicates', 6, ...
            'notes', "Day2 C5 physical proxy: higher angle, lower SNR, mid-to-high xpol"), ...
        struct( ...
            'candidate_id', "CTRL_NEG", ...
            'expected_regime', "negative_control_high_eps_wall", ...
            'antenna_type', "patch_ffd", ...
            'eps_values', [7.0], ...
            'xpol_values', [22, 30, 38], ...
            'inc_values', [20, 45, 65], ...
            'snr_values', [15, 25, 35], ...
            'placements', {{'wall_x', 'wall_y'}}, ...
            'replicates', 2, ...
            'notes', "Patch negative control inspired by Day1 wall harm cells"), ...
        struct( ...
            'candidate_id', "C1", ...
            'expected_regime', "ideal_upper_bound_low_eps_broad", ...
            'antenna_type', "ideal", ...
            'eps_values', [2.5, 4.5], ...
            'xpol_values', [22, 30, 38], ...
            'inc_values', [20, 45, 65], ...
            'snr_values', [15, 25, 35], ...
            'placements', {{'floor'}}, ...
            'replicates', 1, ...
            'notes', "Sparse ideal upper-bound control for C1"), ...
        struct( ...
            'candidate_id', "C2", ...
            'expected_regime', "ideal_upper_bound_mid_xpol_hotspot", ...
            'antenna_type', "ideal", ...
            'eps_values', [2.5, 4.5], ...
            'xpol_values', [30], ...
            'inc_values', [20, 45, 65], ...
            'snr_values', [15, 25, 35], ...
            'placements', {{'floor'}}, ...
            'replicates', 1, ...
            'notes', "Sparse ideal upper-bound control for C2"), ...
        struct( ...
            'candidate_id', "C5", ...
            'expected_regime', "ideal_upper_bound_low_confidence_probe", ...
            'antenna_type', "ideal", ...
            'eps_values', [2.5, 4.5], ...
            'xpol_values', [30, 38], ...
            'inc_values', [45, 65], ...
            'snr_values', [15, 25], ...
            'placements', {{'floor'}}, ...
            'replicates', 1, ...
            'notes', "Sparse ideal upper-bound control for C5"), ...
        struct( ...
            'candidate_id', "CTRL_NEG", ...
            'expected_regime', "ideal_upper_bound_negative_control", ...
            'antenna_type', "ideal", ...
            'eps_values', [7.0], ...
            'xpol_values', [22, 30, 38], ...
            'inc_values', [20, 45, 65], ...
            'snr_values', [15, 25, 35], ...
            'placements', {{'wall_x'}}, ...
            'replicates', 1, ...
            'notes', "Sparse ideal negative-control anchor")};

    rows = {};
    case_id = 0;
    for b = 1:numel(blocks)
        block = blocks{b};
        for i_eps = 1:numel(block.eps_values)
            for i_xpol = 1:numel(block.xpol_values)
                for i_inc = 1:numel(block.inc_values)
                    for i_snr = 1:numel(block.snr_values)
                        for i_place = 1:numel(block.placements)
                            placement = string(block.placements{i_place});
                            for rep = 1:block.replicates
                                case_id = case_id + 1;
                                geom = replicateGeometry(block.inc_values(i_inc), placement, rep);
                                rows(end + 1, :) = { ...
                                    case_id, ...
                                    string(seed_stage_id), ...
                                    double(seed_base), ...
                                    block.eps_values(i_eps), ...
                                    tan_delta, ...
                                    block.xpol_values(i_xpol), ...
                                    block.snr_values(i_snr), ...
                                    block.inc_values(i_inc), ...
                                    string(block.antenna_type), ...
                                    string(block.candidate_id), ...
                                    rep, ...
                                    string(block.expected_regime), ...
                                    string(block.notes), ...
                                    string(seed_stage_id), ...
                                    double(seed_base), ...
                                    material_name, ...
                                    geom.anchor_height, ...
                                    geom.tag_height, ...
                                    geom.tag_x, ...
                                    geom.tag_y, ...
                                    ar_edge_db, ...
                                    slab_size_base + geom.slab_size_delta, ...
                                    geom.slab_tilt_deg, ...
                                    string(placement), ...
                                    false, ...
                                    1, ...
                                    geom.geometry_descriptor}; %#ok<AGROW>
                            end
                        end
                    end
                end
            end
        end
    end

    cases = cell2table(rows, 'VariableNames', { ...
        'case_id', 'seed_stage_id', 'seed_base', 'eps_r', 'tan_delta', 'xpol_coupling_db', 'snr_db', ...
        'incidence_deg', 'antenna_type', 'candidate_id', 'replicate_id', 'expected_regime', 'notes', ...
        'stage_id', 'base_seed', 'material_name', 'anchor_height', 'tag_height', 'tag_x', 'tag_y', ...
        'ar_edge_db', 'slab_size_m', 'slab_tilt_deg', 'slab_placement', 'los_blockage', 'num_slabs', 'geometry_descriptor'});

    cases.tx_height = cases.anchor_height;
    cases.rx_height = cases.tag_height;
    cases.los_angle_target_deg = cases.incidence_deg;
    cases = movevars(cases, {'stage_id', 'base_seed'}, 'After', 'seed_base');

    sort_key = compose(string(cases.antenna_type) + "|" + string(cases.candidate_id) + "|" + string(cases.slab_placement));
    [~, order] = sort(sort_key);
    cases = cases(order, :);
    cases.case_id = (1:height(cases)).';

    meta = struct();
    meta.seed_stage_id = seed_stage_id;
    meta.seed_base = seed_base;
    meta.source_day2_csv = string(candidate_csv_path);
    meta.shortlist = shortlist(ismember(string(shortlist.candidate_id), required_ids), :);
    meta.total_cases = height(cases);
    meta.patch_cases = sum(strcmpi(cases.antenna_type, 'patch_ffd'));
    meta.ideal_cases = sum(strcmpi(cases.antenna_type, 'ideal'));
    meta.candidate_counts = localCandidateCounts(cases);
end

function geom = replicateGeometry(incidence_deg, placement, replicate_id)
    anchor_base = 2.5;
    tag_base = 0.5;
    y_offsets = [0.00, -0.10, 0.10, -0.18, 0.18, -0.24, 0.24, -0.12, 0.12, 0.06];
    anchor_delta = [0.00, 0.04, -0.04, 0.07, -0.07, 0.03, -0.03, 0.08, -0.08, 0.05];
    tag_delta = [0.00, -0.03, 0.03, -0.05, 0.05, -0.02, 0.02, -0.06, 0.06, 0.04];
    slab_size_delta = [0.00, 0.15, -0.15, 0.25, -0.25, 0.10, -0.10, 0.20, -0.20, 0.05];
    slab_tilt = [0.0, 1.5, -1.5, 2.5, -2.5, 1.0, -1.0, 3.0, -3.0, 0.5];

    idx = mod(double(replicate_id) - 1, numel(y_offsets)) + 1;
    anchor_height = anchor_base + anchor_delta(idx);
    tag_height = max(0.20, tag_base + tag_delta(idx));

    radius = max(0.15, (anchor_height - tag_height) * tand(double(incidence_deg)));
    tag_y = y_offsets(idx);
    if abs(tag_y) >= radius
        tag_y = sign(tag_y + eps) * 0.60 * radius;
    end
    tag_x_mag = max(0.08, sqrt(max(radius.^2 - tag_y.^2, 0.0)));

    placement = lower(char(string(placement)));
    switch placement
        case 'floor'
            tag_x = tag_x_mag;
            tag_y = tag_y;
        case 'ceiling'
            tag_x = tag_x_mag;
            tag_y = -tag_y;
        case 'wall_x'
            tag_x = tag_x_mag;
            tag_y = abs(tag_y);
        case 'wall_y'
            tag_x = abs(tag_y);
            tag_y = max(0.08, tag_x_mag);
        otherwise
            error('Unsupported placement: %s', placement);
    end

    geom = struct();
    geom.anchor_height = anchor_height;
    geom.tag_height = tag_height;
    geom.tag_x = tag_x;
    geom.tag_y = tag_y;
    geom.slab_size_delta = slab_size_delta(idx);
    geom.slab_tilt_deg = slab_tilt(idx);
    geom.geometry_descriptor = sprintf('rep%d_ah%.2f_th%.2f_ty%.2f', replicate_id, anchor_height, tag_height, tag_y);
end

function tbl = localCandidateCounts(cases)
    [G, cand, ant] = findgroups(string(cases.candidate_id), string(cases.antenna_type));
    counts = splitapply(@numel, cases.case_id, G);
    tbl = table(cand, ant, counts, 'VariableNames', {'candidate_id', 'antenna_type', 'case_count'});
end
