function mat = materialsLibrary(name)
% materialsLibrary - return predefined indoor material models.
%
% Available:
%   'wood', 'glass', 'concrete', 'metal_pec', 'drywall',
%   'brick', 'ceramic_tile', 'vacuum'

    key = lower(char(string(name)));
    switch key
        case 'wood'
            mat = core.Material( ...
                'kind', 'dielectric', ...
                'eps_r', 2.0, ...
                'tan_delta', 0.02, ...
                'xpol_coupling_db', 30.0, ...
                'name', 'wood');
        case 'glass'
            mat = core.Material( ...
                'kind', 'dielectric', ...
                'eps_r', 6.0, ...
                'tan_delta', 0.001, ...
                'xpol_coupling_db', 40.0, ...
                'name', 'glass');
        case 'concrete'
            mat = core.Material( ...
                'kind', 'dielectric', ...
                'eps_r', 5.5, ...
                'tan_delta', 0.05, ...
                'xpol_coupling_db', 25.0, ...
                'name', 'concrete');
        case 'drywall'
            mat = core.Material( ...
                'kind', 'dielectric', ...
                'eps_r', 2.5, ...
                'tan_delta', 0.02, ...
                'xpol_coupling_db', 28.0, ...
                'name', 'drywall');
        case 'brick'
            mat = core.Material( ...
                'kind', 'dielectric', ...
                'eps_r', 4.0, ...
                'tan_delta', 0.02, ...
                'xpol_coupling_db', 27.0, ...
                'name', 'brick');
        case 'ceramic_tile'
            mat = core.Material( ...
                'kind', 'dielectric', ...
                'eps_r', 10.0, ...
                'tan_delta', 0.005, ...
                'xpol_coupling_db', 38.0, ...
                'name', 'ceramic_tile');
        case 'metal_pec'
            mat = core.Material( ...
                'kind', 'PEC', ...
                'pec_tm_sign', -1.0, ...
                'xpol_coupling_db', 45.0, ...
                'name', 'metal_pec');
        case 'vacuum'
            mat = core.Material( ...
                'kind', 'dielectric', ...
                'eps_r', 1.0, ...
                'tan_delta', 0.0, ...
                'xpol_coupling_db', 60.0, ...
                'name', 'vacuum');
        otherwise
            error('materials:materialsLibrary:UnknownMaterial', 'Unknown material: %s', char(string(name)));
    end
end
