function surf = makeSurface(surface_id, name, point, normal, u_axis, v_axis, half_u, half_v, material)
% makeSurface - compact rectangular-plane helper for sanity scenes.

    surf = core.Surface( ...
        'surface_id', surface_id, ...
        'name', name, ...
        'point', point(:), ...
        'normal', normal(:), ...
        'u_axis', u_axis(:), ...
        'v_axis', v_axis(:), ...
        'half_u', half_u, ...
        'half_v', half_v, ...
        'material', material);
end
