function results = runImplementedChecks()
% runImplementedChecks - execute the 10 implemented Day 4 sanity checks.

    sanity.ensureOutputDir();
    checks = { ...
        @sanity.checkA1_losPathLoss, ...
        @sanity.checkA2_singleBouncePath, ...
        @sanity.checkA3_snellLaw, ...
        @sanity.checkA4_pathEnumeration, ...
        @sanity.checkB1_cpHandednessReversal, ...
        @sanity.checkB3_brewsterAngle, ...
        @sanity.checkB4_normalIncidence, ...
        @sanity.checkC1_losCirPeak, ...
        @sanity.checkC2_uwbPulseShape, ...
        @sanity.checkD2_couplingUnitarity};

    result_cells = cell(numel(checks), 1);
    for idx = 1:numel(checks)
        result_cells{idx, 1} = checks{idx}();
        fprintf('%s: %s\n', result_cells{idx}.name, ternary(result_cells{idx}.passed, 'PASS', 'FAIL'));
    end
    results = vertcat(result_cells{:});
end

function out = ternary(cond, true_value, false_value)
    if cond
        out = true_value;
    else
        out = false_value;
    end
end
