projectRoot = fileparts(fileparts(mfilename('fullpath')));
addpath(genpath(projectRoot));

cfg = config.defaultConfig();
outDir = fullfile(cfg.results_dir, 'week25');
if ~exist(outDir, 'dir')
    mkdir(outDir);
end

tx_pos = [0; 0; 1];
rx_pos = [2; 0; 1];
scene = core.Scene();
paths = trace.enumeratePaths(scene, tx_pos, rx_pos, 0);
assert(numel(paths) == 1 && paths.bounce_count == 0, 'Expected exactly one LoS path');

tx_linear_ideal = core.Antenna( ...
    'position', tx_pos, ...
    'boresight', [1; 0; 0], ...
    'h_axis', [0; 1; 0], ...
    'v_axis', [0; 0; 1], ...
    'basis', 'linear', ...
    'enable_coupling', false, ...
    'tx_peak_gain_dbi', 0.0, ...
    'rx_peak_gain_dbi', 0.0, ...
    'tx_pattern_cos_exp', 0.0, ...
    'rx_pattern_cos_exp', 0.0);
rx_linear_ideal = core.Antenna( ...
    'position', rx_pos, ...
    'boresight', [-1; 0; 0], ...
    'h_axis', [0; 1; 0], ...
    'v_axis', [0; 0; 1], ...
    'basis', 'linear', ...
    'enable_coupling', false, ...
    'tx_peak_gain_dbi', 0.0, ...
    'rx_peak_gain_dbi', 0.0, ...
    'tx_pattern_cos_exp', 0.0, ...
    'rx_pattern_cos_exp', 0.0);

tx_linear_patch = core.Antenna( ...
    'position', tx_pos, ...
    'boresight', [1; 0; 0], ...
    'h_axis', [0; 1; 0], ...
    'v_axis', [0; 0; 1], ...
    'basis', 'linear', ...
    'cross_pol_leakage_db', 20.0, ...
    'axial_ratio_db', 3.0, ...
    'enable_coupling', true, ...
    'tx_peak_gain_dbi', 0.0, ...
    'rx_peak_gain_dbi', 0.0, ...
    'tx_pattern_cos_exp', 0.0, ...
    'rx_pattern_cos_exp', 0.0);
rx_linear_patch = core.Antenna( ...
    'position', rx_pos, ...
    'boresight', [-1; 0; 0], ...
    'h_axis', [0; 1; 0], ...
    'v_axis', [0; 0; 1], ...
    'basis', 'linear', ...
    'cross_pol_leakage_db', 20.0, ...
    'axial_ratio_db', 3.0, ...
    'enable_coupling', true, ...
    'tx_peak_gain_dbi', 0.0, ...
    'rx_peak_gain_dbi', 0.0, ...
    'tx_pattern_cos_exp', 0.0, ...
    'rx_pattern_cos_exp', 0.0);

tx_circ_ideal = antennas.makeIdealCpAntenna('right', tx_pos, [1; 0; 0], [0; 1; 0], [0; 0; 1]);
rx_circ_ideal = antennas.makeIdealCpAntenna('right', rx_pos, [-1; 0; 0], [0; 1; 0], [0; 0; 1]);
pattern = antennas.loadPatchPatternSynthetic('ar_db_boresight', 3.0, 'xpd_db_boresight', 20.0, 'peak_gain_dbi', 0.0, 'fitted_cos_exp', 0.0);
tx_circ_patch = antennas.makeRealisticPatchAntenna(pattern, tx_pos, [1; 0; 0], [0; 1; 0], [0; 0; 1]);
rx_circ_patch = antennas.makeRealisticPatchAntenna(pattern, rx_pos, [-1; 0; 0], [0; 1; 0], [0; 0; 1]);

rows = [ ...
    summarize('linear_ideal_to_linear_patch', tx_linear_ideal, rx_linear_patch, paths, cfg); ...
    summarize('linear_patch_to_linear_ideal', tx_linear_patch, rx_linear_ideal, paths, cfg); ...
    summarize('linear_patch_to_linear_patch', tx_linear_patch, rx_linear_patch, paths, cfg); ...
    summarize('circular_ideal_to_circular_patch', tx_circ_ideal, rx_circ_patch, paths, cfg); ...
    summarize('circular_patch_to_circular_ideal', tx_circ_patch, rx_circ_ideal, paths, cfg); ...
    summarize('circular_patch_to_circular_patch', tx_circ_patch, rx_circ_patch, paths, cfg)];

resultTbl = cell2table(rows, 'VariableNames', {'link', 'basis', 'abs_H11_mid', 'abs_H21_mid', 'gamma_mid'});
csvPath = fullfile(outDir, 'diag_linear_vs_circular_patch.csv');
writetable(resultTbl, csvPath);

reportPath = fullfile(outDir, 'diag_linear_vs_circular_patch.md');
fid = fopen(reportPath, 'w');
assert(fid ~= -1, 'Failed to open %s', reportPath);
cleanup = onCleanup(@() fclose(fid)); %#ok<NASGU>

fprintf(fid, '# Linear vs Circular Patch Diagnostic\n\n');
fprintf(fid, '- Geometry: pure LoS, boresight aligned.\n');
fprintf(fid, '- Parameters: `AR=3 dB`, `XPD=20 dB`.\n');
fprintf(fid, '- Mixed links reveal whether coupling is active; matched links reveal whether it cancels.\n\n');
fprintf(fid, '| link | basis | |H(1,1)| mid | |H(2,1)| mid | gamma mid |\n');
fprintf(fid, '| --- | --- | ---: | ---: | ---: |\n');
for i = 1:height(resultTbl)
    fprintf(fid, '| %s | %s | %.6g | %.6g | %.6g |\n', ...
        resultTbl.link{i}, resultTbl.basis{i}, resultTbl.abs_H11_mid(i), ...
        resultTbl.abs_H21_mid(i), resultTbl.gamma_mid(i));
end

fprintf('Saved:\n');
fprintf('  %s\n', csvPath);
fprintf('  %s\n', reportPath);

function row = summarize(label, tx_ant, rx_ant, paths, cfg)
    H = channel.buildChannel(paths, tx_ant, rx_ant, cfg.freqs);
    mid = ceil(numel(cfg.freqs) / 2);
    if strcmpi(tx_ant.basis, 'linear')
        basis = 'linear';
    else
        basis = 'circular';
    end
    row = {label, basis, abs(H(1, 1, mid)), abs(H(2, 1, mid)), safeRatio(abs(H(2, 1, mid)), abs(H(1, 1, mid)))};
end

function value = safeRatio(num, den)
    if den <= 0
        value = NaN;
    else
        value = num / den;
    end
end
