function names = canonicalFeatureNames()
% canonicalFeatureNames - canonical 18-feature set for Week 3 Stage 1 modeling.
%
% CP features retained:
%   gamma_cp_1_freq_avg
%   gamma_cp_2_freq_db
%   gamma_cp_3_fp_only
%   gamma_cp_6_phase_circvar
%   a_fp_2_peak_to_total
%   a_fp_6_fp_to_2nd_peak
%
% CIR baseline features retained:
%   rms_delay_spread
%   mean_excess_delay
%   max_excess_delay
%   fp_to_total_ratio
%   rise_time_fp
%   fp_kurtosis
%   kurtosis_total
%   skewness_total
%   energy_concentration_50ns
%   num_significant_peaks
%   peak_to_avg_ratio
%   k_factor_estimate

    names = { ...
        'gamma_cp_1_freq_avg', ...
        'gamma_cp_2_freq_db', ...
        'gamma_cp_3_fp_only', ...
        'gamma_cp_6_phase_circvar', ...
        'a_fp_2_peak_to_total', ...
        'a_fp_6_fp_to_2nd_peak', ...
        'rms_delay_spread', ...
        'mean_excess_delay', ...
        'max_excess_delay', ...
        'fp_to_total_ratio', ...
        'rise_time_fp', ...
        'fp_kurtosis', ...
        'kurtosis_total', ...
        'skewness_total', ...
        'energy_concentration_50ns', ...
        'num_significant_peaks', ...
        'peak_to_avg_ratio', ...
        'k_factor_estimate'};
end
