function feats = canonicalizeFeatureStruct(feats)
% canonicalizeFeatureStruct - prune raw feature aliases down to the canonical 18.

    if nargin < 1 || isempty(feats)
        feats = struct();
        return;
    end

    keep = [metadataNames(), features.canonicalFeatureNames()];
    fields = fieldnames(feats);
    for i = 1:numel(fields)
        if ~ismember(fields{i}, keep)
            feats = rmfield(feats, fields{i});
        end
    end
end

function names = metadataNames()
    names = { ...
        'idx_fp', ...
        't_fp_s', ...
        'fp_peak_val', ...
        'fp_method', ...
        'primary_tx_port', ...
        'primary_rx_port', ...
        'tx_handedness', ...
        'gamma_cp_same_tx_port', ...
        'gamma_cp_same_rx_port', ...
        'gamma_cp_reversed_rx_port'};
end
