function names = rhLhCp16FeatureNames()
% rhLhCp16FeatureNames - fixed CP_all_RH_LH_16 audit feature names.

    names = { ...
        'xpr_fp_db', ...
        'xpr_late_db', ...
        'xpr_all_db', ...
        's3_fp', ...
        's3_late', ...
        's3_all', ...
        'delta_tau_l_given_r_s', ...
        'delta_p_l_given_r_db', ...
        'f_r_fp', ...
        'f_l_fp', ...
        'delta_f_l_minus_r_fp', ...
        'lambda_l_late_fraction', ...
        'gamma_anchor_linear', ...
        'gamma_delay_linear', ...
        'cp_phase_slope_delay_s', ...
        'cp_phase_residual_circvar'};
end
